services:
  db:
    image: postgres:17.2
    volumes:
      - this-again-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    env_file:
      - .env
    ports:
      - 7000:3000
    volumes:
      - .:/rails
      - this-again-gems:/bundle
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/development

volumes:
  this-again-db:
  this-again-gems:
